# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec60dc956580c1503b9305d200814517ad9d734a631a7cf016f82f2ff6a754f623eddf7f22728d3ccc978826bbea6547164ff899d3ced9aa567790fc104a19fc

test:
  secret_key_base: 0a2adbdc64b3b08ef7f65980c66917f9c14e6f58ac7ced3360b8b90042f97306970bddbc5dbfb1e5a5e334e7fa583e4377ed80dea45ebcdf2cbc2c178cd0a15d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
